apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: voting-app
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: vote-pod
    app: voting-app