apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-dep
  labels:
    name: vote-dep
    app: voting-app
spec:
  template:
    metadata:
      name: vote-pod
      labels:
        name: vote-pod
        app: voting-app
    spec:
      containers:
      - name: vote
        image: docker/example-voting-app-vote
        ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      name: vote-pod
      app: voting-app