apiVersion: v1
kind: Pod
metadata:
  name: vote-pod
  labels:
    name: vote-pod
    app: voting-app
spec:
  containers:
    - name: vote
      image: docker/example-voting-app-vote
      ports:
        - containerPort: 80